### ISSUE TITLE
Raw identifier still not working

### ISSUE THREAD

**Issue by Tenshock** [yassun7010/serde_valid#17]
Hello, thanks for the fast update refering https://github.com/yassun4dev/serde_valid/issues/13!

I checked the fix and when I run your test I have the following error:

```bash
error: expected expression, found keyword `type`
    |
157 |     #[rule(sample_rule(type))]
    |                        ^^^^ expected expression

error: proc-macro derive produced unparsable tokens
    |
153 |     #[derive(Validate)]
    |              ^^^^^^^^

error: could not compile `test_app` (lib test) due to 2 previous errors
```

my version:
* `rustc 1.71.0 (8ede3aae2 2023-07-12)`
* `serde_valid = "0.16.3"`

Did I miss something?

**Comment by yassun4dev** [comment]
[My test case](serde_valid/tests/specific_test.rs) is working well in rustc 1.71.

Do you get the same result when you run the same code?

**Comment by yassun7010** [comment]
I will close this Issue until someone else encounters the same problem.
