### ISSUE TITLE
Error type is difficuit

### ISSUE THREAD

**Issue by ollyde** [yassun7010/serde_valid#59]
I would like if this library follows the rust standard where errors are a type we can manage and handle.

For example

```
object_to_validate.validate().unwrap_err()
```

This just returns a default error type with no way to infer what happened.

**Comment by yassun7010** [comment]
Since validate returns a Result, what you want is already possible.

In response to this Issue, I have modified the code in the readme sample to be [simpler](https://github.com/yassun7010/serde_valid/pull/62/files).
