### ISSUE TITLE
`pro-macro-error` is unmaintained -- RUSTSEC-2024-0370

### ISSUE THREAD

**Issue by eismont21** [yassun7010/serde_valid#83]
The `serde_valid_derive` is using an unmaintained dependency `pro-macro-error`, which is flagged in [RUSTSEC-2024-0370](https://rustsec.org/advisories/RUSTSEC-2024-0370).

I encountered this issue while running `cargo-deny check`, which failed due to this security advisory. It seems that a possible solution is to replace it with `proc-macro-error2`.

**Comment by yassun7010** [comment]
I released [v0.25.0](https://github.com/yassun7010/serde_valid/tree/v0.25.0) 👍
